"""order for frontend1

Revision ID: 038b14e4d7e0
Revises: 08ee2bbecfeb
Create Date: 2024-10-19 12:19:57.937172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '038b14e4d7e0'
down_revision = '08ee2bbecfeb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('email', sa.String(), nullable=True))
    op.add_column('order', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'description')
    op.drop_column('order', 'email')
    # ### end Alembic commands ###
