"""order for frontend

Revision ID: 08ee2bbecfeb
Revises: e313069eac5f
Create Date: 2024-10-19 12:18:27.858233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ee2bbecfeb'
down_revision = 'e313069eac5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('name', sa.String(), nullable=True))
    op.add_column('order', sa.Column('phoneNumber', sa.String(), nullable=True))
    op.add_column('order', sa.Column('address', sa.String(), nullable=True))
    op.drop_column('order', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('order', 'address')
    op.drop_column('order', 'phoneNumber')
    op.drop_column('order', 'name')
    # ### end Alembic commands ###
