"""favorite init23

Revision ID: 3237054d2e92
Revises: 8ccc7c3e6a0c
Create Date: 2024-08-18 16:21:17.689726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3237054d2e92'
down_revision = '8ccc7c3e6a0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    # ### end Alembic commands ###
