"""Add size and color

Revision ID: 65a1488f3a8c
Revises: 7180903aa197
Create Date: 2025-01-07 00:02:41.546106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65a1488f3a8c'
down_revision = '7180903aa197'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('col', sa.String(), nullable=True, unique=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sizes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('size', sa.String(), nullable=True, unique=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('product', sa.Column('Image_urls', sa.String(), nullable=True))
    op.add_column('product', sa.Column('Color', sa.String(), nullable=True))
    op.add_column('product', sa.Column('size', sa.String(), nullable=True))
    op.drop_constraint('product_image_urls_fkey', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'sizes', ['size'], ['size'])
    op.create_foreign_key(None, 'product', 'colors', ['Color'], ['col'])
    op.create_foreign_key(None, 'product', 'image_urls', ['Image_urls'], ['url'])
    op.drop_column('product', 'image_urls')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('image_urls', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('product_image_urls_fkey', 'product', 'image_urls', ['image_urls'], ['url'])
    op.drop_column('product', 'size')
    op.drop_column('product', 'Color')
    op.drop_column('product', 'Image_urls')
    op.drop_table('sizes')
    op.drop_table('colors')
    # ### end Alembic commands ###
