"""Products initi

Revision ID: 6c179a4595bc
Revises: dd2457a2378a
Create Date: 2024-07-28 00:54:47.296344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c179a4595bc'
down_revision = 'dd2457a2378a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
