"""image_urls add

Revision ID: 7180903aa197
Revises: fc88f3aeddaf
Create Date: 2025-01-04 16:57:26.693814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7180903aa197'
down_revision = 'fc88f3aeddaf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_urls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(), nullable=True, unique=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('product', sa.Column('image_urls', sa.String(), nullable=True))
    op.create_foreign_key(None, 'product', 'image_urls', ['image_urls'], ['url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'image_urls')
    op.drop_table('image_urls')
    # ### end Alembic commands ###
