"""favorite init

Revision ID: 8ccc7c3e6a0c
Revises: 5320d2765be3
Create Date: 2024-08-18 16:17:45.893095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ccc7c3e6a0c'
down_revision = '5320d2765be3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
