"""order code add

Revision ID: 9578dd0e8183
Revises: 038b14e4d7e0
Create Date: 2024-10-19 23:17:59.807189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9578dd0e8183'
down_revision = '038b14e4d7e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('Code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'Code')
    # ### end Alembic commands ###
