"""order total price add

Revision ID: c4f1701d3a7b
Revises: 9578dd0e8183
Create Date: 2024-10-27 19:15:50.027809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4f1701d3a7b'
down_revision = '9578dd0e8183'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'price')
    # ### end Alembic commands ###
