"""Products init

Revision ID: dd2457a2378a
Revises: d5e01d74a20b
Create Date: 2024-07-26 16:21:16.949787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd2457a2378a'
down_revision = 'd5e01d74a20b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
