"""order payment methods

Revision ID: fc88f3aeddaf
Revises: 5b2b6fdf3878
Create Date: 2024-11-17 00:32:09.516046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc88f3aeddaf'
down_revision = '5b2b6fdf3878'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('Payment_method', sa.String(), nullable=True))
    op.drop_column('order', 'Payment method')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('Payment method', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('order', 'Payment_method')
    # ### end Alembic commands ###
